In [120]:
import numpy as np

**Data Types and Attributes**

In [121]:
#Numpy has only one type of data : ndarray i.e. n dimentional array
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [122]:

type(a1)

numpy.ndarray

In [123]:
a2 = np.array([
    [1,2,3.3],
    [4,5,6.5]
])

In [124]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [125]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [126]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

![Failed To Load](anatomy.png)

In [127]:
a1.shape  #Way of numpy dosent show 1

(3,)

In [128]:
a2.shape

(2, 3)

In [129]:
a3.shape

(3, 2, 3)

In [130]:
a1.ndim, a2.ndim, a3.ndim #This gives dimentions of a1, a2, a3

(1, 2, 3)

In [131]:
a1.size, a2.size, a3.size #Gives size i.e. number of elements

(3, 6, 18)

In [132]:
a1.dtype, a2.dtype, a3.dtype  #Gives the data type

(dtype('int64'), dtype('float64'), dtype('int64'))

In [133]:
import pandas as pd
df = pd.DataFrame(a2)
df   #Create df a2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

**Creating Arrays**

In [134]:
#Create a np array of ones
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [135]:
type(ones)

numpy.ndarray

In [136]:
ones.dtype

dtype('float64')

In [137]:
zeroes = np.zeros((2,2))
zeroes

array([[0., 0.],
       [0., 0.]])

In [138]:
#Create range array
range_array = np.arange(0 ,10,2)  #From 0 to 10 in step 2

In [139]:
range_array

array([0, 2, 4, 6, 8])

In [140]:
#Create random array 
random_array = np.random.randint(0 , 10 , size = (2,3))  #Creates a 2 * 3 array of random integers between 0 (inclusive) and 10 (exclusive)
random_array

array([[0, 9, 5],
       [2, 0, 3]], dtype=int32)

In [141]:
random_array_2 = np.random.random((5,3))   #Creates 5 * 3 wil values [0,1)
random_array_2

array([[0.73731786, 0.4501238 , 0.62088786],
       [0.1923302 , 0.95396688, 0.9362178 ],
       [0.02762457, 0.10663826, 0.36806689],
       [0.80667244, 0.89860205, 0.86469759],
       [0.16415311, 0.01524146, 0.93348319]])

In [142]:
random_array_3= np.random.rand(5,3)  #Second Method
random_array_3

array([[0.63072253, 0.88703046, 0.02531142],
       [0.94891577, 0.26712886, 0.25739642],
       [0.2583454 , 0.89303385, 0.33095757],
       [0.36232258, 0.96126124, 0.40416685],
       [0.565395  , 0.62786883, 0.52136014]])

**Viewing arrays and matrices**


In [143]:
#View number of unique elements in random_array
np.unique(random_array)

array([0, 2, 3, 5, 9], dtype=int32)

In [144]:
#Note: a1 is 1D a2 is 2D and a3 is 3D
a1[0]


np.int64(1)

In [145]:
a2[0]


array([1. , 2. , 3.3])

In [146]:

a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

**Manipulating Arrays**

In [147]:
a1

array([1, 2, 3])

In [148]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [149]:
a1 + ones

array([2., 3., 4.])

In [150]:
a2 / a1 

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [151]:
a2 // a1 #Floor division i.e. rounds down

array([[1., 1., 1.],
       [4., 2., 2.]])

In [152]:
a2 ** 2  #Squares a2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [153]:
np.exp(a1)  #takes exponential

array([ 2.71828183,  7.3890561 , 20.08553692])

In [154]:
np.log(a1)   #Takes logarithm

array([0.        , 0.69314718, 1.09861229])

In [155]:
#Use python method on python datatypes and numpy method on numpy datatypes
listy_list = [5,4,3,2,1]
listy_list

[5, 4, 3, 2, 1]

In [156]:
a1

array([1, 2, 3])

In [157]:
sum(listy_list)

15

In [158]:
np.sum(a1)

np.int64(6)

In [159]:
np.std(a2)   #Computes standard deviation of a2

np.float64(1.8226964152656422)

In [160]:
#Variance: Jati dherai teti higher range of numbers
higher = np.array([1,100,4000])
lower = np.array([1,2,3])
np.var(higher) , np.var(lower)

(np.float64(3467978.0), np.float64(0.6666666666666666))

In [161]:
np.std(higher) , np.std(lower)

(np.float64(1862.2507886963024), np.float64(0.816496580927726))

In [162]:
#Two arrays are only compatible when theya re equal or one of the dimentions is one 
#Otherwise we need to reshape array
#a2 * a3  This raises error

In [163]:
#We have to reshape
a2_reshape = a2.reshape(3,2,1)   #Reshapes to this dimention
a2_reshape

array([[[1. ],
        [2. ]],

       [[3.3],
        [4. ]],

       [[5. ],
        [6.5]]])

In [164]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ]],

       [[ 23.1,  26.4,  29.7],
        [ 40. ,  44. ,  48. ]],

       [[ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [167]:
a2.T #Transposes: Flips the axes|

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [169]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

mat1 * mat2   #Hadamard product  i.e. element wise

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [ ]:
#Matrix product : Dot product
#np.dot(mat1,mat2)   #For matrix product dimentions must be n * m = m * p so this gives error


![Failed To Load](product.png)

In [172]:
#So we may product these matrix my tranposing i.e. swapping dimentions
mat1_transposed = mat1.T 
np.dot(mat1_transposed,mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]], dtype=int32)

In [173]:
#Comparing
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [174]:
a1 == a1

array([ True,  True,  True])

In [175]:
random_array


array([[0, 9, 5],
       [2, 0, 3]], dtype=int32)

In [176]:
np.sort(random_array)

array([[0, 5, 9],
       [0, 2, 3]], dtype=int32)

In [178]:
np.argsort(random_array)   #Sorts the index 

array([[0, 2, 1],
       [1, 0, 2]])

In [179]:
#Store images as numpy array
from matplotlib.image import imread
panda = imread("panda.png")
type(panda)

numpy.ndarray